services:

  app:
    build: .
    container_name: money-manager-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/moneymanager
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret

  postgres:
    image: postgres:16
    container_name: postgres_container_MM
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: moneymanager
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
