version: "3.8"

services:

  app:
    build: .
    container_name: money-manager
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/moneymanager
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret

  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: moneymanager
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment: 
      PGADMIN_DEFAULT_EMAIL: jairojjr@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports: 
      - "89:80"
    depends_on:
      - postgres
    networks: 
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
